# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := ms
DEFS_Debug := \
	'-D__STDC_FORMAT_MACROS=1'

# Flags passed to all source files.
CFLAGS_Debug := \
	-Wall \
	-Werror \
	-m64 \
	-mcx16 \
	-mtune=native \
	-ffast-math \
	-fno-builtin-malloc \
	-fno-builtin-calloc \
	-fno-builtin-realloc \
	-fno-builtin-free \
	-fno-omit-frame-pointer \
	-fno-exceptions \
	-O0 \
	-gdwarf-2

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-std=c++11 \
	-fno-rtti

INCS_Debug := \
	-I. \
	-Isrc

DEFS_Release := \
	'-D__STDC_FORMAT_MACROS=1'

# Flags passed to all source files.
CFLAGS_Release := \
	-Wall \
	-Werror \
	-m64 \
	-mcx16 \
	-mtune=native \
	-ffast-math \
	-fno-builtin-malloc \
	-fno-builtin-calloc \
	-fno-builtin-realloc \
	-fno-builtin-free \
	-fno-omit-frame-pointer \
	-fno-exceptions \
	-O3

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-std=c++11 \
	-fno-rtti

INCS_Release := \
	-I. \
	-Isrc

OBJS := \
	$(obj).target/$(TARGET)/src/benchmark/std_glue/glue_ms_queue.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,--as-needed

LDFLAGS_Release := \
	-Wl,--as-needed

LIBS :=

$(obj).target/libms.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libms.a: LIBS := $(LIBS)
$(obj).target/libms.a: TOOLSET := $(TOOLSET)
$(obj).target/libms.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/libms.a
# Add target alias
.PHONY: ms
ms: $(obj).target/libms.a

# Add target alias to "all" target.
.PHONY: all
all: ms

