# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := prodcon-ms
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,--as-needed

LDFLAGS_Release := \
	-Wl,--as-needed

LIBS := \
	-lpthread \
	-lgflags

$(builddir)/prodcon-ms: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/prodcon-ms: LIBS := $(LIBS)
$(builddir)/prodcon-ms: LD_INPUTS := $(obj).target/libscal.a $(obj).target/libprodcon-base.a $(obj).target/libms.a
$(builddir)/prodcon-ms: TOOLSET := $(TOOLSET)
$(builddir)/prodcon-ms: $(obj).target/libscal.a $(obj).target/libprodcon-base.a $(obj).target/libms.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/prodcon-ms
# Add target alias
.PHONY: prodcon-ms
prodcon-ms: $(builddir)/prodcon-ms

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/prodcon-ms

